### ISSUE TITLE
Why do you handle auth?

### ISSUE THREAD

**Issue by elgalu** [BrynMawrCollege/jupyterhub#2]
Hi, I'm a bit lost maybe but I don't get why do you handle login and account here.

Shouldn't that be the solely responsibility of JupterHub already existing auth?

**Comment by dsblank** [comment]
Why do you think we handle auth? JupyterHub does handle both login and accounts.

**Comment by elgalu** [comment]
Ah ok, so when you `Sign in with {{login_service}}` you delegate to JupterHub auth?

What about this: [Create Jupyter Accounts](https://github.com/BrynMawrCollege/jupyterhub/blob/master/accounts.py#L30) ?

**Comment by dsblank** [comment]
Yes, JupyterHub handles all logins.

The accounts service will allow an admin to create user accounts from the web interface.
